### PR TITLE
use internal crate to share make table functions

### PR DESCRIPTION
**Pull request by mrhooray**
cc @vitiral 
plan to publish new version after land this

### CODE REVIEW

**Comment by vitiral** [comment]
Looks great, much better than copy/paste! Thanks for pushing this past the finish line :)

My only comment would be to include a doc-comment at the top of `util/lib.rs` to say why it exists.

**Comment by mrhooray** [comment]
@vitiral 
looks like cargo doesn't support publishing crates with internal crates according to https://github.com/rust-lang/cargo/issues/1565
any suggestions besides publishing this internal crate shared by source and build script?

**Comment by vitiral** [comment]
It looks like the only solution is to publish the library crate separately.

There might actually be some value to that in this case, as someone might want to create different tables but not depend on this crate. Would it be too much to publish a `crc-core` crate or something and then depend on it?

I'm sorry, I could have sworn I saw a crate that used a path dependency work. Obviously I was mistaken.

**Comment by mrhooray** [comment]
That's find. Just wanted to check in case we have alternatives.

**Comment by mrhooray** [comment]
@vitiral just published new version with external crate approach

**Pull request merged**
