### PR TITLE
Use intel crc32 instruction

### PR DESCRIPTION
**Pull request by kubo39**
Use intel crc32 instruction (SSE4.2) via x86intrin crate when `RUSTFLAGS="-C target-feature=+sse4.2" cargo build --features=simd-accel`.

### CODE REVIEW

**Comment by kubo39** [comment]
@mrhooray ping?

**Comment by mrhooray** [comment]
@kubo39 the speed up is substantial, what do you think of this in relation with #10?

In addition, would this conflict with the goal of #11 #13 by introducing dependencies that cannot have in embedded environments? It looks like `x86intrin` is optional but wanted to confirm.

**Comment by oyvindln** [comment]
>Is there a particular reason this is only applied to castagnoli but no others, or it's just an example?

That's the only one there is a crc32 instruction for in SSE.

**Comment by mrhooray** [comment]
@kubo39 this is really cool however it adds certain complexity to the code and only apply to one variance. seems like #10 has better win across the board and would love to get it merged.

**Pull request closed without merging**
