### PR TITLE
no_std example build

### PR DESCRIPTION
**Pull request by mrhooray**

### CODE REVIEW

**Comment by mrhooray** [comment]
@vitiral @sbourdeauducq both `no_std.rs` example and `no_std` crate compiled successfully based upon current master. are they actually valid examples using no_std?

@vitiral when trying `cargo test --features no_std` on nightly like the ones in #13, it complains `error: Package 'crc v1.5.0 (file:///.../rui/crc-rs)' does not have these features: 'no_std'`, wondering what was your setup?

**Comment by vitiral** [comment]
The "standard" (there is no standard...) way is to run it with:
```
cargo test --no-default-features
```

Basically it was done in reverse: `std` is a "default feature" and you disable it for `no_std` crates.

**Comment by mrhooray** [comment]
@vitiral thanks, tried that and it built & passed the tests. Do you see master it not working for no_std?

**Comment by vitiral** [comment]
the current way of having `default = ["std"]` in `Cargo.toml` is conventional and correct I believe.

**Pull request closed without merging**
