### PR TITLE
Avoid a direct dependency on build_const

### PR DESCRIPTION
**Pull request by whitequark**
See rust-lang/cargo#4866 for explanation.

### CODE REVIEW

**Comment by mrhooray** [comment]
lgtm if this is what it takes
@vitiral any suggestions/concerns?

**Comment by mrhooray** [comment]
@whitequark do you think of a test for nostd support so that we don't regress in the future?

**Comment by whitequark** [comment]
@mrhooray I don't think this test can be written without a custom rustc sysroot.

**Comment by vitiral** [comment]
This looks good. I think it is a probably a good idea to avoid a direct dependency. I only added it for convienience in the first place and it does almost the exact same thing.

That bug is a pretty interesting one. Makes `build_const` quite a bit less ergonomic :(

**Comment by vitiral** [comment]
sorry about breaking nostd @whitequark, and thanks for fixing!

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
